# Generated by Django 3.2.5 on 2022-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsList',
            fields=[
                ('date', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
