# Generated by Django 3.2.5 on 2022-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='000000', max_length=255)),
                ('user', models.CharField(default='anoy', max_length=255)),
                ('content', models.CharField(default='nan', max_length=255)),
                ('score', models.CharField(default='0', max_length=255)),
                ('version', models.CharField(default=' ', max_length=255)),
                ('name', models.CharField(default='outlook', max_length=255)),
                ('msgid', models.CharField(default='nan', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_huawei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='anoy', max_length=255)),
                ('comment', models.CharField(default=' ', max_length=255)),
                ('operTime', models.CharField(default='000000', max_length=255)),
                ('phone', models.CharField(default=' ', max_length=255)),
                ('rating', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
