# Generated by Django 3.2.5 on 2022-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_huawei',
            name='appname',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
