# Generated by Django 3.2.5 on 2022-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20220729_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='huaweiComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='anoy', max_length=255)),
                ('comment', models.CharField(default=' ', max_length=255)),
                ('operTime', models.CharField(default='000000', max_length=255)),
                ('phone', models.CharField(default=' ', max_length=255)),
                ('rating', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
