# Generated by Django 3.2.5 on 2022-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20220810_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_oppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='000000', max_length=255)),
                ('user', models.CharField(default='anoy', max_length=255)),
                ('content', models.CharField(default='nan', max_length=255)),
                ('score', models.CharField(default='0', max_length=255)),
                ('version', models.CharField(default=' ', max_length=255)),
                ('name', models.CharField(default=' ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='000000', max_length=255)),
                ('user', models.CharField(default='anoy', max_length=255)),
                ('content', models.CharField(default='nan', max_length=255)),
                ('score', models.CharField(default='0', max_length=255)),
                ('version', models.CharField(default=' ', max_length=255)),
                ('name', models.CharField(default=' ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_yingyongbao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='000000', max_length=255)),
                ('user', models.CharField(default='anoy', max_length=255)),
                ('content', models.CharField(default='nan', max_length=255)),
                ('score', models.CharField(default='0', max_length=255)),
                ('version', models.CharField(default=' ', max_length=255)),
                ('name', models.CharField(default=' ', max_length=255)),
            ],
        ),
    ]
